package com.mkanchwala.country.beans;

// Generated 24 May, 2015 1:17:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CountryLanguage generated by hbm2java
 */
@Entity
@Table(name = "country_translation")
public class CountryTranslation extends BaseBean {

	private static final long serialVersionUID = -3335573875545541221L;
	private Integer countryTranslationId;
	private Language language;
	private Country country;
	private String createdBy;
	private Date dateCreated;
	private Date lastUpdated;
	private String lastUpdatedBy;
	private String localName;
	private String capital;
	private String description;

	public CountryTranslation() {
	}

	public CountryTranslation(Language language, Country country,
			Date dateCreated, String localName, String capital) {
		this.language = language;
		this.country = country;
		this.dateCreated = dateCreated;
		this.localName = localName;
		this.capital = capital;
	}

	public CountryTranslation(Language language, Country country,
			String createdBy, Date dateCreated, Date lastUpdated,
			String lastUpdatedBy, String localName, String capital,
			String description) {
		this.language = language;
		this.country = country;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
		this.localName = localName;
		this.capital = capital;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "country_translation_id", unique = true, nullable = false)
	public Integer getCountryTranslationId() {
		return this.countryTranslationId;
	}

	public void setCountryTranslationId(Integer countryTranslationId) {
		this.countryTranslationId = countryTranslationId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "name", nullable = false)
	public Language getLanguage() {
		return this.language;
	}

	public void setLanguage(Language language) {
		this.language = language;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "code", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by")
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Column(name = "local_name", nullable = false)
	public String getLocalName() {
		return this.localName;
	}

	public void setLocalName(String localName) {
		this.localName = localName;
	}

	@Column(name = "capital", nullable = false)
	public String getCapital() {
		return this.capital;
	}

	public void setCapital(String capital) {
		this.capital = capital;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
