package com.mkanchwala.country.beans;

// Generated 24 May, 2015 1:17:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country")
public class Country extends BaseBean {

	private static final long serialVersionUID = -9191999645596142646L;
	private String code;
	private String createdBy;
	private Date dateCreated;
	private Date lastUpdated;
	private String lastUpdatedBy;
	private String worldName;
	private Long population;
	private Set<CountryTranslation> countryTranslations = new HashSet<CountryTranslation>(0);

	public Country() {
	}

	public Country(String code, Date dateCreated, String worldName) {
		this.code = code;
		this.dateCreated = dateCreated;
		this.worldName = worldName;
	}

	public Country(String code, String createdBy, Date dateCreated,
			Date lastUpdated, String lastUpdatedBy, String worldName,
			Long population, Set<CountryTranslation> countryTranslations) {
		this.code = code;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
		this.worldName = worldName;
		this.population = population;
		this.countryTranslations = countryTranslations;
	}

	@Id
	@Column(name = "code", unique = true, nullable = false, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by")
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@Column(name = "world_name", nullable = false)
	public String getWorldName() {
		return this.worldName;
	}

	public void setWorldName(String worldName) {
		this.worldName = worldName;
	}

	@Column(name = "population")
	public Long getPopulation() {
		return this.population;
	}

	public void setPopulation(Long population) {
		this.population = population;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<CountryTranslation> getCountryTranslations() {
		return this.countryTranslations;
	}

	public void setCountryTranslations(Set<CountryTranslation> countryTranslations) {
		this.countryTranslations = countryTranslations;
	}

}
