package com.mkanchwala.country.beans;

// Generated 24 May, 2015 1:17:04 PM by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "language")
public class Language extends BaseBean {

	private static final long serialVersionUID = -4283587613980136853L;
	private String name;
	private String createdBy;
	private Date dateCreated;
	private String description;
	private Date lastUpdated;
	private String lastUpdatedBy;
	private Set<CountryTranslation> countryTranslations = new HashSet<CountryTranslation>(0);
	private Set<User> users = new HashSet<User>(0);

	public Language() {
	}

	public Language(String name, Date dateCreated) {
		this.name = name;
		this.dateCreated = dateCreated;
	}

	public Language(String name, String createdBy, Date dateCreated,
			String description, Date lastUpdated, String lastUpdatedBy,
			Set<CountryTranslation> countryTranslations, Set<User> users) {
		this.name = name;
		this.createdBy = createdBy;
		this.dateCreated = dateCreated;
		this.description = description;
		this.lastUpdated = lastUpdated;
		this.lastUpdatedBy = lastUpdatedBy;
		this.countryTranslations = countryTranslations;
		this.users = users;
	}

	@Id
	@Column(name = "name", unique = true, nullable = false)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "created_by")
	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 19)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_updated", length = 19)
	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	@Column(name = "last_updated_by")
	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<CountryTranslation> getCountryTranslations() {
		return this.countryTranslations;
	}

	public void setCountryTranslations(Set<CountryTranslation> countryTranslations) {
		this.countryTranslations = countryTranslations;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}
}